#!/usr/bin/env python3
"""Render a deterministic Markdown view of the canonical ANDON closure ledger."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Iterable

from check_andon_closure_ledger import LIVE_LEDGER, ROOT, git_head, materialize_fixture, rel, validate_ledger


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def _cell(value: Any) -> str:
    if isinstance(value, list):
        text = ", ".join(str(item) for item in value) if value else "none"
    elif value is None:
        text = "none"
    else:
        text = str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _evidence_line(evidence: dict[str, Any]) -> str:
    details = [
        f"kind={_cell(evidence.get('kind'))}",
        f"source={_cell(evidence.get('source_ref'))}",
    ]
    for label, key in (
        ("commit", "commit_sha1"),
        ("blob", "blob_sha1"),
        ("sha256", "sha256"),
        ("command", "command"),
        ("exit", "exit_code"),
        ("retained", "retained_artifact"),
        ("unretained_reason", "unretained_reason"),
    ):
        value = evidence.get(key)
        if value is not None:
            details.append(f"{label}={_cell(value)}")
    return "; ".join(details)


def render(document: dict[str, Any]) -> str:
    lines = [
        "<!-- GENERATED by tools/render_andon_closure_ledger.py; DO NOT EDIT. -->",
        "# DAEE v0.4.6.0-wip ANDON Closure Ledger",
        "",
        "> Structural control-plane view only. This document does not claim semantic truth, model behavior, candidate maturity, package readiness, release readiness, or interlocutor uptake.",
        "",
        "## Ledger identity",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Ledger | `{_cell(document.get('ledger_id'))}` |",
        f"| Source head | `{_cell(document.get('source_head'))}` |",
        f"| Branch | `{_cell(document.get('branch'))}` |",
        f"| Overall status | `{_cell(document.get('overall_status'))}` |",
        f"| Regression status | `{_cell(document.get('regression_status'))}` |",
        "",
        "## ANDON rows",
        "",
        "| ID | Priority | Status | Bounded verified | Integration open | Owner gated | Artifact gated | Terminal open | Dependencies | Next action |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in document.get("rows", []):
        lines.append(
            f"| `{_cell(row.get('andon_id'))}` | `{_cell(row.get('priority'))}` | "
            f"`{_cell(row.get('status'))}` | `{_cell(row.get('bounded_verified'))}` | "
            f"`{_cell(row.get('integration_open'))}` | `{_cell(row.get('owner_gated'))}` | "
            f"`{_cell(row.get('artifact_gated'))}` | `{_cell(row.get('terminal_open'))}` | "
            f"{_cell(row.get('dependencies', []))} | {_cell(row.get('next_action'))} |"
        )
    lines.extend(["", "## Milestones", ""])
    for row in document.get("rows", []):
        lines.extend([f"### {_cell(row.get('andon_id'))}: {_cell(row.get('title'))}", ""])
        for milestone in row.get("milestones", []):
            lines.append(
                f"- `{_cell(milestone.get('milestone_id'))}` — `{_cell(milestone.get('status'))}`; "
                f"depends on: {_cell(milestone.get('depends_on', []))}."
            )
        lines.extend([
            "",
            f"Owner sources: {_cell(row.get('owner_sources', []))}.",
            "",
            "Remaining joins:",
            "",
        ])
        for join in row.get("remaining_joins", []):
            lines.append(f"- {_cell(join)}")
        lines.extend([
            "",
            "Scope exclusions:",
            "",
        ])
        for exclusion in row.get("scope_exclusions", []):
            lines.append(f"- {_cell(exclusion)}")
        lines.extend([
            "",
            "Evidence references:",
            "",
        ])
        for evidence in row.get("evidence_refs", []):
            lines.append(f"- {_evidence_line(evidence)}")
        lines.extend([
            "",
            f"Remaining risk: {_cell(row.get('remaining_risk', []))}.",
            "",
        ])
    lines.extend(["## Non-claims", ""])
    for statement in document.get("non_claims", []):
        lines.append(f"- {_cell(statement)}")
    lines.append("")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", default=rel(LIVE_LEDGER), help="canonical ledger JSON")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--out", help="write generated Markdown")
    group.add_argument("--check", help="fail if this generated Markdown is stale")
    group.add_argument("--self-test", action="store_true", help="run deterministic in-memory checks")
    return parser


def main(argv: Iterable[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if not (args.out or args.check or args.self_test):
        build_parser().error("one of --out, --check, or --self-test is required")
    ledger_path = Path(args.ledger)
    if not ledger_path.is_absolute():
        ledger_path = ROOT / ledger_path
    try:
        document = materialize_fixture(ledger_path, LIVE_LEDGER)
    except ValueError as exc:
        print(f"andon closure ledger renderer: FAIL: {exc}")
        return 1
    findings = validate_ledger(document, expected_head=git_head())
    if findings:
        print(f"andon closure ledger renderer: FAIL [{findings[0].failure_class}]: {findings[0].message}")
        return 1
    expected = render(document)
    if args.self_test:
        repeated = render(json.loads(json.dumps(document)))
        required = [
            "<!-- GENERATED by tools/render_andon_closure_ledger.py; DO NOT EDIT. -->",
            "Structural control-plane view only.",
            "Bounded verified",
            "Integration open",
            "Owner gated",
            "Artifact gated",
            "Terminal open",
            "Remaining joins:",
            "Evidence references:",
            "## Non-claims",
        ]
        problems = [marker for marker in required if marker not in expected]
        if repeated != expected:
            problems.append("render is not stable across an equivalent JSON round trip")
        if "\r" in expected or not expected.endswith("\n"):
            problems.append("render must use LF and end with one newline")
        if problems:
            for problem in problems:
                print(f"FAIL: {problem}")
            print(f"andon closure ledger renderer self-test: FAIL ({len(problems)} problem(s))")
            return 1
        print("andon closure ledger renderer self-test: PASS")
        return 0
    target_value = args.out or args.check
    target = Path(target_value)
    if not target.is_absolute():
        target = ROOT / target
    if args.check:
        try:
            actual = target.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"andon closure ledger renderer: STALE ({rel(target)} missing)")
            return 1
        if actual != expected:
            print(f"andon closure ledger renderer: STALE ({rel(target)})")
            return 1
        print(f"andon closure ledger renderer: PASS ({rel(target)})")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8", newline="\n")
    print(f"andon closure ledger renderer: WROTE ({rel(target)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
